services:
  whoami:
    image: traefik/whoami                       # Use the whoami image
    labels:
      - "traefik.enable=true"                   # Enable Traefik for this service
      - "traefik.http.routers.whoami123.rule=Host(`whoami.localhost`)" # Host rule for routing
      - "traefik.http.services.whoami123.loadbalancer.server.port=80"

  apache:
    image: httpd:latest                         # Use the official Apache HTTP Server image
    labels:
      - "traefik.enable=true"                   # Enable Traefik for this service
      - "traefik.http.routers.apache456.rule=Host(`apache.localhost`)" # Host rule for routing
      - "traefik.http.services.apache456.loadbalancer.server.port=80"

